---
name: R10k Deployment

on:
  push:
    paths:
      - 'Puppetfile'
      - 'modules/**'
      - 'code/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install r10k
        run: sudo gem install r10k

      - name: Deploy changes with r10k
        working-directory: /etc/puppetlabs/code/environments/git/main
        run: |
          sudo /usr/local/bin/r10k deploy environment -p
