---
name: R10k Deployment

on:
  push:
    paths:
      - 'Puppetfile'
      - 'modules/**'
      - 'code/**'
jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install r10k
        run: sudo gem install r10k

      - name: Deploy changes with r10k
        #working-directory: /etc/puppetlabs/code/environments/git/main
        run: |
          #sudo /usr/local/bin/r10k deploy evironment -pv
          cd /etc
          ls -l
          echo "Operating System: ${{ runner.os }}"
          echo "Runner Labels: ${{ runner.labels }}"
          echo "Environment Variables:"
          env
